@startuml
hide stereotype
!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Server/all.puml

skinparam actorStyle awesome

together {
osa_server(server1, "POC Network", "Application Server")
osa_server(server2, "Server Network 1", "Target Server 1")
osa_server(server3, "Server Network 2", "Target Server 2")
}

osa_desktop(pc, "User Network", "PC")


server1 -[hidden]> server3
server2 -[hidden]> server1

server1 -[#red]l-> server2: X - port 22
server1 -[#green]r-> server3: port 123
server1 -[dotted,#blue]-> pc: Reverse Tunnel

pc -u[dotted,#blue]-> server2: Reverse Tunnel
pc -u[#yellow]-> server1: SSH Connection
pc -u[#green]-> server2: port 22
pc -u[#green]-> server3: port 123
:User: -u-> pc
@enduml
